### ISSUE TITLE
Xử lý từng input 

### ISSUE THREAD

**Issue by phuctd99** [sonbeo1999hd/frontend-practice#2]
![8](https://user-images.githubusercontent.com/43601776/61697147-e3b0ef00-ad60-11e9-9419-c8bd678cdbea.PNG)
Khi để trống click sẽ hiện liên tiếp 3 thông báo

**Comment by sonbeo1999hd** [comment]
thì chỗ nào chưa điền nó thông báo ra mà ông :))))

**Comment by phuctd99** [comment]
thỏa mãn từng yêu cầu một chứ, không nó ra một loạt thì k hay

**Comment by sonbeo1999hd** [comment]
ok

**Comment by sonbeo1999hd** [comment]
đã fix!
