### ISSUE TITLE
Button hover tệ

### ISSUE THREAD

**Issue by idist-hn** [sonbeo1999hd/frontend-practice#3]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/21170584/61697217-017e5400-ad61-11e9-9369-ba9fa02d8b0d.png">
Nên đọc thêm các bài ví dụ như [](https://uxdesign.cc/ui-cheat-sheets-buttons-7329ed9d6112)

**Comment by sonbeo1999hd** [comment]
e đã đổi lại màu, xin ý kiến từ a ạ
