### ISSUE TITLE
Nên quan tâm các trình duyệt khác nhau

### ISSUE THREAD

**Issue by idist-hn** [sonbeo1999hd/frontend-practice#4]
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/21170584/61697590-c2043780-ad61-11e9-9d65-f9cf0afa06bf.png">

các trình duyệt sẽ render css khác nhau. nên tìm hiểu và chú ý hơn các điểm này. có thể đẹp trên mọi trình duyệt là tốt nhất

**Comment by sonbeo1999hd** [comment]
vâng ạ
